config/routes.rb
Tracker::Application.routes.draw do
  
  
  root :to => 'users#index'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  resources :users do
    collection do
      get 'checkcreate'
      get 'showallmessagesnow'
      get 'showallusersnow'
    end
  end
  resources :imeilists
  resources :messages do 
    collection do
      get "changed"
    end
    member do
      get "strange"
    end

  end

end

app/models/imeilist.rb
class Imeilist < ActiveRecord::Base
  attr_accessible :imei, :user_id

  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :date, :imei, :name, :number, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :imei , :name , :cnic , :address	
  # attr_accessible :title, :body
  has_many :imeilists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  
 
end

app/controllers/imeilists_controller.rb
class ImeilistsController < ApplicationController
  before_filter :authenticate_user!
  def new
  	@imeilist = Imeilist.new;
  end

  def create
  	@imeilist = Imeilist.new(params[:imeilist])
  	if(@imeilist.save!)
  		redirect_to imeilists_path, :success => "IMEI number added successfully."
  	end
  end

  def index
		@imeilist = Imeilist.where(["user_id = ?", current_user.id])
  end

  def destroy
  	Imeilist.destroy(params[:id])
  	redirect_to imeilists_path
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def index
		@thread = Imeilist.where(["user_id = ?", current_user.id]).pluck(:imei)
		@t = Imeilist.where(["user_id = ?", current_user.id])
		#@thread = Imeilist.find(:all,:select => 'imei', :conditions => { user_id = current_user } )
		@messages = Message.where(:imei => @thread)
	

		#Client.where(:orders_count => [1,3,5])
		# @thread = Imeilist.where(user_id: current_user)
		# @thread_ids = Imeilist.where(user_id: current_user).pluck(:id)
		
		# @messages = Message.where(imei: @thread_ids)
	end

	def show
		@message = Message.find(params[:id])
	end

	def changed
		# return render json: params[:imei]
		begin
			if params[:imei].to_i
		@t = Imeilist.where(["user_id = ?", current_user.id])
		if params[:imei].present?
			@messages = Message.where(imei: params[:imei])
		else
			@thread = Imeilist.where(["user_id = ?", current_user.id]).pluck(:imei)
			@messages = Message.where(:imei => @thread)
		end
	end
		rescue Exception  => e

		end
	end

	def strange
		
		
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :checkcreate, :showallmessagesnow, :showallusersnow]
  def index
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end
  def showallmessagesnow
    @messages = Message.all
  end
  def showallusersnow
    @user = User.all
  end
  def checkcreate
    @message = Message.new
    sms_from = params['sms_from']
    sms_body = params['sms_body']


    sms_from = sms_from.gsub("\"",'') 
    sms_body = sms_body.gsub("\"",'')

     arr = sms_from.split(' ')
     len = arr.length 
     @message.imei = arr[0].to_s
     @message.number = arr[1].to_s
     @message.name = ""
    i = 2 

    while i < len-2 
      @message.name=@message.name+" "+ arr[i] 
      i = i +1 
    end 
    @message.date = arr[len-2].to_s+" "+arr[len-1].to_s 
    @message.body = sms_body
    @message.save!


  end 

  def update
  	@user = User.find(params[:id])
    # @component.description = params[:description]
    # @component.name = params[:name]
    # @component.save!
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_path, success: 'User was successfully updated.' }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imeilists_helper.rb
module ImeilistsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/imeilists/index.html.erb
<div class="container">  
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <h1 class="text-center login-title">My IMEI numbers List</h1><br><br>
      <div class="account-wall">
      	<% if @imeilist.blank? %>
      	<h4> No IMEI Number Registered Yet <h4>
      	<% else %>
				<% @imeilist.try(:each) do |ime| %>
					<table class ="table table-striped">
						<tr id="myrow">
							<td><%= ime.try(:imei) %></td>
							<td>
								<div class="pull-right">
									<%#= form_tag imeilist_path(ime.id),:method => :delete, :remote => true do %>
										<%#= submit_tag 'Delete',:class => 'btn btn-primary'%>
									<%# end %>
									<%= link_to 'Delete',imeilist_path(ime.id),:method => :delete %>
								</div>
							</td>
						</tr>
					</table>
				<% end %>
				<% end %>
      </div>
    </div>
  </div>
</div>

app/views/imeilists/new.html.erb
<div class="container">  
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <h1 class="text-center login-title">Add IMEI number</h1><br><br><br><br>
      <div class="account-wall">

				<%= form_for @imeilist do |f| %>
					<%= f.hidden_field :user_id, value:  current_user.id %>
				  <div>
					  <%= f.label :IMEI %><br>
					  <%= f.text_field :imei, autofocus: true,class: "form-control" %><br><br>
					</div>

				  <div><%= f.submit "Add IMEI" , class: "btn btn-lg btn-block", style: "background-color:#666;color:white" %>
				  </div>
				<% end %>

      </div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
   <%= stylesheet_link_tag "http://netdna.bootstrapcdn.com/bootstrap/3.0.0-rc2/css/bootstrap-glyphicons.css" %>


  <%= csrf_meta_tags %>
</head>
	<body>
		<br> <br> <br>
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		  <div class="navbar-header">
		    <a class="navbar-brand" href="<%= root_url %>">Home</a>
		  </div>
		  <div class="container">
		  	<% if current_user %>
		    <ul class="nav navbar-nav">
		      <li><a href="<%= user_path(current_user) if current_user%>"> Profile </a></li>
		    </ul>
		     <ul class="nav navbar-nav">
		      <li><a href="<%= new_imeilist_path %>"> Add IMEI </a></li>
		    </ul>
		    <ul class="nav navbar-nav">
		      <li><a href="<%= imeilists_path %>"> IMEI List </a></li>
		    </ul>
		     <ul class="nav navbar-nav">
		      <li><a href="<%= messages_path %>"> Messages </a></li>
		    </ul>
		    <% end %>
		    <ul class="nav navbar-nav pull-right" >
		      <% if user_signed_in? %>
		      	<li style = "margin-top:15px;">
					  	<strong><%= link_to current_user.email, edit_user_path(current_user)%></strong>
					  </li>
						<li>
						  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
						</li>
					<% else %>
						<li> 
						  <%= link_to "Sign up", new_user_registration_path %> 	
						</li>
						<li>
						  <%= link_to "Login", new_user_session_path %>
						</li>
					<% end %>	
				</ul>
			</div>
		</nav>
		
		<div class="container" style="margin-top:70px;">
		<% flash.each do |name, msg| %>
		  <% if msg.is_a?(String) %>
		    <% name = name.to_s == 'success' ? 'success' : name.to_s %>
		    <% name = name.to_s == 'alert' ? 'danger' : name.to_s %>
		  <% name = name.to_s == 'notice' ? 'info' : name.to_s %>    
		    <div class="alert alert-<%= name %> main-alert">
		      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		      <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
		    </div>
		  <% end %>
		<% end %>

		<%= yield %>
</div>
	</body>
</html>

app/views/messages/changed.html.erb
<div class="container">  
  <div class="row">

    <div class="col-sm-2 col-md-12 col-md-offset-1">
     
<div class="row">



      <div class="col-md-2">
      <h1 class="text-center login-title">Messages</h1>
    </div>
      <%= form_for :imeilist, :url => {:action => :changed}, method: :get do |f| %>
    		<div class="col-md-5 input-group" style="padding-top:25px;max-width:200px;margin-left:15px;">
      	<%=select_tag :imei, options_for_select(@t.collect{ |u| [u.imei] }),:prompt => 'All', class: 'form-control' %>
    		<span class="input-group-btn">
			    <button class="btn" type="submit"><span class="glyphicon glyphicon-search">
    			</span></button>
			  </span>
			  <!-- <span class="input-group-addon">
    			<span class="glyphicon glyphicon-search">
    			</span>
    		</span> -->
    </div>
    <% end %>
    		</div>
      <div class="account-wall">
      	<% if params[:imei] != ''%>
      		<h4> Now Showing <%= params[:imei] %> </h4>
      	<% else %>
      		<h4> Now Showing All Messages </h4>
      	<% end %>
      	<% if @messages.blank? %>
      	<h4> No Message to show Yet </h4>
      	<% else %>
      	<table class ="table" style="width:800px">
						<thead bgcolor="grey">
							<td>
								Sender Name
							</td>
							<td>
								Sender Number
							</td>
							<td>
								Date & Time
							</td>
							<td>
								IMEI
							</td>
							<td>
								Text Body
							</td>
						</thead>
				<% @messages.try(:each) do |msg| %>
					<tbody>
						<tr id="myrow">
							<td>
								<%= msg.try(:name) %>
							</td>
							<td>
								<%= msg.try(:number) %>
							</td>
							<td>
								<%= msg.try(:date) %>
							</td>
							<td>
								<%= msg.try(:imei) %>
							</td>
							<td>
								<%= truncate(msg.try(:body), :length => 15) %>
								<%= link_to "(Continued)", message_path(msg) %> 
							</td>
						</tr>

				<% end %>
				</tbody>
					</table>	
				<% end %>



      </div>
		</div>
	</div>
</div>

app/views/messages/index.html.erb
<div class="container">  
  <div class="row">

    <div class="col-sm-2 col-md-12 col-md-offset-1">
     
<div class="row">



      <div class="col-md-2">
      <h1 class="text-center login-title">Messages</h1>
    </div>
      <%= form_for :imeilist, :url => {:action => :changed}, method: :get do |f| %>
    		<div class="col-md-5 input-group" style="padding-top:25px;max-width:200px;margin-left:15px;">
      	<%=select_tag :imei, options_for_select(@t.collect{ |u| [u.imei] }),:prompt => 'All', class: 'form-control' %>
    		<span class="input-group-btn">
			    <button class="btn" type="submit"><span class="glyphicon glyphicon-search">
    			</span></button>
			  </span>
			  <!-- <span class="input-group-addon">
    			<span class="glyphicon glyphicon-search">
    			</span>
    		</span> -->
    </div>
    <% end %>
    		</div>
      <div class="account-wall">
      	<% if @messages.blank? %>
      	<h4> No Message to show Yet </h4>
      	<% else %>
      	<table class ="table" style="width:800px">
						<thead bgcolor="grey">
							<td>
								Sender Name
							</td>
							<td>
								Sender Number
							</td>
							<td>
								Date & Time
							</td>
							<td>
								IMEI
							</td>
							<td>
								Text Body
							</td>
						</thead>
				<% @messages.try(:each) do |msg| %>
					<tbody>
						<tr id="myrow">
							<td>
								<%= msg.try(:name) %>
							</td>
							<td>
								<%= msg.try(:number) %>
							</td>
							<td>
								<%= msg.try(:date) %>
							</td>
							<td>
								<%= msg.try(:imei) %>
							</td>
							<td>
								<%= truncate(msg.try(:body), :length => 15) %>
								<%= link_to "(Continued)", message_path(msg.id) %> 
							</td>
						</tr>

				<% end %>
				</tbody>
					</table>	
				<% end %>



      </div>
		</div>
	</div>
</div>

app/views/messages/show.html.erb
<div class="container">  
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <h1 class="text-center login-title">Message</h1><br><br>
      <div class="account-wall">

				 <dl class="dl-horizontal">
				  <dt><strong>Sender Name</strong></dt>
				  <dd><%= @message.name %></dd>
				  <dt><strong>Sender Number:</strong></dt>
				  <dd><%= @message.number %></dd>
				  <dt><strong>Date</strong></dt>
				  <dd><%= @message.date %></dd>
				  <dt><strong>IMEI:</strong></dt>
				  <dd><%= @message.imei %></dd>
				  <dt><strong>Message Body:</strong></dt>
				  <dd><%= @message.body %></dd>
				</dl>
				
       </div>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container">  
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <h1 class="text-center login-title">Edit Your Profile</h1>
      <div class="account-wall">

				<%= form_for @user , :url => {:action => :update}, method: :put do |f| %>
				  <div><%= f.label :email %><br />
				  <%= f.email_field :email ,class: "form-control" %>
					</div>
					<div><%= f.label :name %><br />
				  <%= f.text_field :name, class: "form-control" %>
					</div>
					<div><%= f.label :cnic %><br />
				  <%= f.text_field :cnic ,class: "form-control" %>
					</div>
					<div><%= f.label :address %><br />
				  <%= f.text_field :address,class: "form-control" %><br>
					</div>

				  <div><%= f.submit "Update" , class: "btn btn-lg btn-block", style: "background-color:#666;color:white" %></div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<h1>Website is enhancing in functionalities.</h1>

app/views/users/show.html.erb
<div class="container">  
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <h1 class="text-center login-title">My Profile</h1><br><br>
      <div class="account-wall">
        <table class ="table">
          <tr >
            <td style = "border:none"> <strong>Name</strong> </td>
            <td style = "border:none"> <%= @user.name %> </td>
          </tr>
          <tr>
            <td style = "border:none"> <strong>Email Address</strong> </td>
            <td style = "border:none"> <%= @user.email %> </td>
          </tr>
          <tr>
            <td style = "border:none"> <strong>CNIC</strong> </td>
            <td style = "border:none"> <%= @user.cnic %> </td>
          </tr>
          <tr>
            <td style = "border:none"> <strong>Address</strong> </td>
            <td style = "border:none"> <%= @user.address %> </td>
          </tr>
           <tr>
            <td style = "border:none"> </td>
            <td style = "border:none">  <%= link_to "Update", edit_user_path(current_user), class: "btn btn-primary btn-lg active" %> </td>
          </tr>
        </table>
        
      </div>
    </div>
  </div>
</div>

app/views/users/showallmessagesnow.html.erb
<div class="container">  
  <div class="row">

    <div class="col-sm-2 col-md-12 col-md-offset-1">
     
<div class="row">



      <div class="col-md-2">
      <h1 class="text-center login-title">Messages</h1>
    </div>
      
    
    		</div>
      <div class="account-wall">
      	<% if @messages.blank? %>
      	<h4> No Message to show Yet </h4>
      	<% else %>
      	<table class ="table" style="width:800px">
						<thead bgcolor="grey">
							<td>
								Sender Name
							</td>
							<td>
								Sender Number
							</td>
							<td>
								Date & Time
							</td>
							<td>
								IMEI
							</td>
							<td>
								Text Body
							</td>
						</thead>
				<% @messages.try(:each) do |msg| %>
					<tbody>
						<tr id="myrow">
							<td>
								<%= msg.try(:name) %>
							</td>
							<td>
								<%= msg.try(:number) %>
							</td>
							<td>
								<%= msg.try(:date) %>
							</td>
							<td>
								<%= msg.try(:imei) %>
							</td>
							<td>
								<%= msg.try(:body) %>
							</td>
							
						</tr>

				<% end %>
				</tbody>
					</table>	
				<% end %>



      </div>
		</div>
	</div>
</div>